#!/bin/bash -e

cd /opt/beachist/admin

sudo -u beachist bash<<'_'

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install node
npm ci

npm run build
_

mkdir -p /var/www
ln -s $(pwd)/build/ /var/www/beachist
systemctl restart nginx.service
